# Production: PostgreSQL
spring.datasource.url=jdbc:postgresql://5.78.157.191:5432/tesis_parkinson
spring.datasource.username=giomar
spring.datasource.password=giomar2003@
spring.datasource.driver-class-name=org.postgresql.Driver

# update: crea/actualiza tablas si no existen. Tras el primer arranque puedes cambiar a validate.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
