server.port=8081
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://5.78.157.191:5432/tesis_parkinson
spring.datasource.username=giomar
spring.datasource.password=giomar2003@

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.leak-detection-threshold=60000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=dev-secret-256-bit-change-in-production-min-32-chars
jwt.expiration-ms=86400000

app.minio.endpoint=http://5.78.157.191:9000
app.minio.access-key=giomar
app.minio.secret-key=giomar2003@

app.n8n.webhook-url=http://5.78.157.191:5678/webhook/parkinson/analyze
app.webhook.recording-secret=

app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
